nginx:
    image: 'nginx:latest'
    ports:
        - '80:80'
    links:
        - phpfpm
    volumes:
        - ./logs/access.log:/var/log/nginx/logs/myapp-access.log
        - ./logs/error.log:/var/log/nginx/logs/myapp-error.log
        - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
        - ./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
        - ./sites:/sites

phpfpm:
    image: 'bitnami/php-fpm:latest'
    restart: always
    ports:
        - '9000:9000'
    volumes:
        - ./sites:/sites
    environment:
        - DOMAIN_NAME=phpfpm

mysql:
    image: 'mariadb:latest'
    ports:
        - '3306:3306'
    environment:
        - MYSQL_ROOT_PASSWORD=kjdtw



